import type { PdfDocument } from '@/types/pdf';
import { PUBLIC_ABOUT_COPY } from '@/lib/company-copy';

export const pdfFixtureDocument: PdfDocument = {
	title: 'AFEEL Company',
	issueDate: '2026.03',
	heroImageUrl: '/images/symbol.svg',
	aboutText: `${PUBLIC_ABOUT_COPY} 스타일링 협찬을 통해 브랜드의 가시성을 높입니다.`,
	contact: {
		email: 'hello@afeelcompany.com',
		phone: '010-0000-0000',
		address: 'Seoul, Korea',
	},
	workItems: [
		{
			id: 'work-01',
			title: 'ROYNINE LOOK 01',
			clientBrandId: null,
			brandName: 'ROYNINE',
			brandLogoUrl: '/pdf-fixtures/logo-01.png',
			celebrityName: null,
			category: '상의',
			imageUrl: '/pdf-fixtures/work-01.png',
			thumbnailUrl: null,
			showOnPdf: true,
			sortOrder: 1,
		},
		{
			id: 'work-02',
			title: 'ROYNINE LOOK 02',
			clientBrandId: null,
			brandName: 'ROYNINE',
			brandLogoUrl: '/pdf-fixtures/logo-01.png',
			celebrityName: null,
			category: '상의',
			imageUrl: '/pdf-fixtures/work-02.png',
			thumbnailUrl: null,
			showOnPdf: true,
			sortOrder: 2,
		},
		{
			id: 'work-03',
			title: 'ROYNINE LOOK 03',
			clientBrandId: null,
			brandName: 'ROYNINE',
			brandLogoUrl: '/pdf-fixtures/logo-01.png',
			celebrityName: null,
			category: '상의',
			imageUrl: '/pdf-fixtures/work-03.png',
			thumbnailUrl: null,
			showOnPdf: true,
			sortOrder: 3,
		},
		{
			id: 'work-04',
			title: 'ROYNINE LOOK 04',
			clientBrandId: null,
			brandName: 'ROYNINE',
			brandLogoUrl: '/pdf-fixtures/logo-01.png',
			celebrityName: null,
			category: '상의',
			imageUrl: '/pdf-fixtures/work-04.png',
			thumbnailUrl: null,
			showOnPdf: true,
			sortOrder: 4,
		},
	],
	clientBrands: [
		{
			id: 'brand-01',
			name: 'CLIENT 01',
			logoUrl: '/pdf-fixtures/logo-01.png',
			sortOrder: 1,
		},
		{
			id: 'brand-02',
			name: 'CLIENT 02',
			logoUrl: '/pdf-fixtures/logo-02.png',
			sortOrder: 2,
		},
	],
	sectionOrder: ['cover', 'about', 'work', 'client', 'contact'],
};
