import type { PdfDocument } from '@/types/pdf';

export const pdfFixtureDocument: PdfDocument = {
	title: 'AFEEL Company',
	issueDate: '2026.03',
	heroImageUrl: '/images/symbol.svg',
	aboutText:
		'어필컴퍼니는 패션 브랜드와 셀럽을 연결하는 PR 에이전시입니다. 브랜드의 톤과 제품 맥락에 맞는 스타일링 포트폴리오를 큐레이션하고, 소개서와 웹, 인스타그램까지 하나의 흐름으로 연결합니다.',
	contact: {
		email: 'hello@afeelcompany.com',
		phone: '010-0000-0000',
		address: 'Seoul, Korea',
	},
	workItems: [
		{
			id: 'work-01',
			title: 'ROYNINE LOOK 01',
			brandName: 'ROYNINE',
			brandLogoUrl: '/pdf-fixtures/logo-01.png',
			celebrityName: null,
			category: '상의',
			imageUrl: '/pdf-fixtures/work-01.png',
			thumbnailUrl: null,
			showOnPdf: true,
			sortOrder: 1,
		},
		{
			id: 'work-02',
			title: 'ROYNINE LOOK 02',
			brandName: 'ROYNINE',
			brandLogoUrl: '/pdf-fixtures/logo-01.png',
			celebrityName: null,
			category: '상의',
			imageUrl: '/pdf-fixtures/work-02.png',
			thumbnailUrl: null,
			showOnPdf: true,
			sortOrder: 2,
		},
		{
			id: 'work-03',
			title: 'ROYNINE LOOK 03',
			brandName: 'ROYNINE',
			brandLogoUrl: '/pdf-fixtures/logo-01.png',
			celebrityName: null,
			category: '상의',
			imageUrl: '/pdf-fixtures/work-03.png',
			thumbnailUrl: null,
			showOnPdf: true,
			sortOrder: 3,
		},
		{
			id: 'work-04',
			title: 'ROYNINE LOOK 04',
			brandName: 'ROYNINE',
			brandLogoUrl: '/pdf-fixtures/logo-01.png',
			celebrityName: null,
			category: '상의',
			imageUrl: '/pdf-fixtures/work-04.png',
			thumbnailUrl: null,
			showOnPdf: true,
			sortOrder: 4,
		},
	],
	clientBrands: [
		{
			id: 'brand-01',
			name: 'CLIENT 01',
			logoUrl: '/pdf-fixtures/logo-01.png',
			sortOrder: 1,
		},
		{
			id: 'brand-02',
			name: 'CLIENT 02',
			logoUrl: '/pdf-fixtures/logo-02.png',
			sortOrder: 2,
		},
	],
	sectionOrder: ['cover', 'about', 'work', 'client', 'contact'],
};
